// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type NewScriptExecution struct {
	TemplateID string `json:"templateId"`
}

type NewScriptTemplate struct {
	ProjectID uuid.UUID `json:"projectId"`
	Script    string    `json:"script"`
}

type NewTransactionExecution struct {
	TemplateID uuid.UUID `json:"templateId"`
	Payer      string    `json:"payer"`
	Signers    []*string `json:"signers"`
}

type NewTransactionTemplate struct {
	ProjectID uuid.UUID `json:"projectId"`
	Script    string    `json:"script"`
}

type UpdateScriptTemplate struct {
	ID     uuid.UUID `json:"id"`
	Script string    `json:"script"`
}

type UpdateTransactionTemplate struct {
	ID     uuid.UUID `json:"id"`
	Index  *int      `json:"index"`
	Script *string   `json:"script"`
}
