// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package playground

import (
	"github.com/google/uuid"
)

type NewScriptExecution struct {
	ProjectID  uuid.UUID `json:"projectId"`
	TemplateID string    `json:"templateId"`
}

type NewScriptTemplate struct {
	ProjectID uuid.UUID `json:"projectId"`
	Script    string    `json:"script"`
}

type NewTransactionExecution struct {
	ProjectID  uuid.UUID `json:"projectId"`
	TemplateID uuid.UUID `json:"templateId"`
	Payer      string    `json:"payer"`
	Signers    []*string `json:"signers"`
}

type NewTransactionTemplate struct {
	ProjectID uuid.UUID `json:"projectId"`
	Script    string    `json:"script"`
}

type UpdateScriptTemplate struct {
	ProjectID  uuid.UUID `json:"projectId"`
	TemplateID uuid.UUID `json:"templateId"`
	Script     string    `json:"script"`
}

type UpdateTransactionTemplate struct {
	TemplateID uuid.UUID `json:"templateId"`
	Index      *int      `json:"index"`
	Script     *string   `json:"script"`
}
