// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package flow_playground_api

type NewScriptExecution struct {
	TemplateID string `json:"templateId"`
}

type NewScriptTemplate struct {
	Script string `json:"script"`
}

type NewTransactionExecution struct {
	TemplateID string    `json:"templateId"`
	Payer      string    `json:"payer"`
	Signers    []*string `json:"signers"`
}

type NewTransactionTemplate struct {
	Script string `json:"script"`
}

type UpdateScriptTemplate struct {
	TemplateID string `json:"templateId"`
	Script     string `json:"script"`
}

type UpdateTransactionTemplate struct {
	TemplateID string `json:"templateId"`
	Script     string `json:"script"`
}
