name: "Deploy to Cloud Run"

on:
  push:

env:
  DOCKER_IMAGE_URL: ${{ vars.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_REPO }}/${{ vars.GCP_APP }}:${{ github.sha }}
  SERVICE: ${{ vars.GCP_SERVICE }}
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # token_format: 'access_token'
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          # service_account: ${{ env.SERVICE_ACCOUNT }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Docker Auth
        run: |-
          docker build -t ${{ env.DOCKER_IMAGE_URL }} --file Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_URL }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.DOCKER_IMAGE_URL }}
